- hosts: servers
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Check Docker status
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        msg: "{{ docker_version.stdout }}"
